name: Update README with latest blog posts
on:
  schedule:
    - cron: '0 * * * *' # run every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install python3-pip
        pip3 install feedparser
    - name: Update README with latest blog posts
      run: |
        python3 update_readme.py
